### ISSUE TITLE
Only extract paper's title or abstract is enough to write a survey?

### ISSUE THREAD

**Issue by CiaoHe** [AutoSurveys/AutoSurvey#1]
Hi, nice work!
The code shows as only abstract and title is extracted and embedded. I doubt whether the title and abstract alone can support the description of an article when writing a survey of a certain direction. If comparing methods or specific indicators, is the method or experiment part also important?

**Comment by GuoQi2000** [comment]
Actually we extract the first 1500 tokens from each paper for generation. Due to the large size of the database, we only provide the abstracts here. We acknowledge that the details of the papers are also important, but in most  do not focus too much on the details. Truncating the papers allows us to include as much context as possible."

**Comment by GuoQi2000** [comment]
Actually we extract the first 1500 tokens from each paper for generation (metioned in out paper). Due to the large size of the database, we only provide the abstracts here. We acknowledge that the details of the papers are also important, but in most scenarios the abstract and introduction can provide enough informations. Truncations also allow us to include more relevant papers in the context.
